# Generated by Django 5.0 on 2024-01-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png', max_length=500),
        ),
    ]
